---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "yurtedgex.name" . }}-controller
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "yurtedgex.name" . }}-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "yurtedgex.name" . }}-role
rules:
  - apiGroups:
    - apps.openyurt.io
    resources:
    - nodepools
    verbs:
    - list
    - watch
  - apiGroups:
      - apps.openyurt.io
    resources:
      - yurtappsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps.openyurt.io
    resources:
      - yurtappsets/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps/status
      - services/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - device.openyurt.io
    resources:
      - edgexes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - device.openyurt.io
    resources:
      - edgexes/finalizers
    verbs:
      - update
  - apiGroups:
      - device.openyurt.io
    resources:
      - edgexes/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "yurtedgex.name" . }}-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "yurtedgex.name" . }}-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "yurtedgex.name" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "yurtedgex.name" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ template "yurtedgex.name" . }}-controller
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "yurtedgex.name" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "yurtedgex.name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ template "yurtedgex.name" . }}-controller
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "yurtedgex.name" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "yurtedgex.name" . }}-proxy-role
subjects:
  - kind: ServiceAccount
    name: {{ template "yurtedgex.name" . }}-controller
    namespace: {{ .Release.Namespace }}
