---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 31095ea9.openyurt.io
kind: ConfigMap
metadata:
  name: {{ template "yurtedgex.name" . }}-config
  namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
  {{- include "yurtedgex.labels" . | nindent 4 }}
  name: {{ template "yurtedgex.name" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
  {{- include "yurtedgex.selectorLabels" . | nindent 6 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  {{- include "yurtedgex.labels" . | nindent 4 }}
  name: {{ template "yurtedgex.name" . }}-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
  {{- include "yurtedgex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
  {{- include "yurtedgex.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
    {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "yurtedgex.name" . }}-controller
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: {{ .Values.imageRegistry }}{{ .Values.rbacProxy.image.repository }}:{{ .Values.rbacProxy.image.tag }}
          imagePullPolicy: {{ quote .Values.rbacProxy.image.pullPolicy }}
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
        - args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
          command:
            - /manager
          image: {{ .Values.imageRegistry }}{{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag }}
          imagePullPolicy: {{ quote .Values.manager.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cert-secret
              readOnly: true
              mountPath: "/tmp/k8s-webhook-server/serving-certs/"
      nodeSelector:
        openyurt.io/is-edge-worker: "false"
      securityContext:
        runAsNonRoot: true
      volumes:
      - name: cert-secret
        secret:
          secretName: {{ template "yurtedgex.name" . }}-admission
