
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v2
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-device-openyurt-io-v1alpha2-edgex
  failurePolicy: Fail
  name: medgex.kb.io.v1alpha2
  rules:
  - apiGroups:
    - device.openyurt.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - edgexes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-device-openyurt-io-v1alpha1-edgex
  failurePolicy: Fail
  name: medgex.kb.io.v1alpha1
  rules:
  - apiGroups:
    - device.openyurt.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - edgexes
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v2
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-device-openyurt-io-v1alpha2-edgex
  failurePolicy: Fail
  name: vedgex.kb.io.v1alpha2
  rules:
  - apiGroups:
    - device.openyurt.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - edgexes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-device-openyurt-io-v1alpha1-edgex
  failurePolicy: Fail
  name: vedgex.kb.io.v1alpha1
  rules:
  - apiGroups:
    - device.openyurt.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - edgexes
  sideEffects: None
