
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.openyurt.io
  resources:
  - nodepools
  verbs:
  - list
  - watch
- apiGroups:
  - apps.openyurt.io
  resources:
  - yurtappsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.openyurt.io
  resources:
  - yurtappsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps/status
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - device.openyurt.io
  resources:
  - edgexes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - device.openyurt.io
  resources:
  - edgexes/finalizers
  verbs:
  - update
- apiGroups:
  - device.openyurt.io
  resources:
  - edgexes/status
  verbs:
  - get
  - patch
  - update
