apiVersion: batch/v1
kind: Job
metadata:
  name:  controller-manager-admission-patch-validating
  namespace: system
spec:
  template:
    metadata:
      name:  edgex-controller-manager-admission-patch-validating
    spec:
      containers:
        - name: patch
          image: oamdev/kube-webhook-certgen:v2.4.1
          imagePullPolicy: IfNotPresent
          args:
            - patch
            - --webhook-name=edgex-validating-webhook-configuration
            - --namespace=default
            - --secret-name=edgex-webhook-certs
            - --patch-failure-policy=Fail
            - --crds={"name":"edgexes.device.openyurt.io","conversion":{"strategy":"Webhook","webhook":{"clientConfig":{"service":{"name":"edgex-webhook-service","namespace":"default","path":"/convert","port":443}},"conversionReviewVersions":["v1"]}}}
            - --patch-validating=true
            - --patch-mutating=false
      restartPolicy: OnFailure
      serviceAccountName: edgex-webhook-certs
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000