apiVersion: batch/v1
kind: Job
metadata:
  name:  controller-manager-admission-create
  namespace: system
spec:
  template:
    metadata:
      name: edgex-controller-manager-admission-create
    spec:
      containers:
        - name: create
          image: oamdev/kube-webhook-certgen:v2.4.1
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host=edgex-webhook-service,edgex-webhook-service.default.svc
            - --namespace=default
            - --secret-name=edgex-webhook-certs
            - --key-name=tls.key
            - --cert-name=tls.crt
      restartPolicy: OnFailure
      serviceAccountName: edgex-webhook-certs
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000