apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webhook-certs
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edgex-webhook-certs
subjects:
  - kind: ServiceAccount
    name: edgex-webhook-certs
    namespace: default