version: hanoi
configmap:
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: common-variables
  data:
    EDGEX_SECURITY_SECRET_STORE: "false"
    Registry_Host: "edgex-core-consul"
    Clients_CoreData_Host: "edgex-core-data"
    Clients_Data_Host: "edgex-core-data"
    Clients_Notifications_Host: "edgex-support-notifications"
    Clients_Metadata_Host: "edgex-core-metadata"
    Clients_Command_Host: "edgex-core-command"
    Clients_Scheduler_Host: "edgex-support-scheduler"
    Clients_RulesEngine_Host: "edgex-kuiper"
    Clients_VirtualDevice_Host: "edgex-device-virtual"
    Databases_Primary_Host: "edgex-redis"
    Service_ServerBindAddr: "0.0.0.0"
    # Required in case old configuration from previous release used.
    # Change to "true" if re-enabling logging service for remote logging
    Logging_EnableRemote: "false"
    # Clients_Logging_Host: edgex-support-logging # un-comment if re-enabling logging service for remote logging
services:
- metadata:
    name: edgex-core-consul
  spec:
    selector:
      app: edgex-core-consul
    ports:
    - name: tcp-8500
      port: 8500
      protocol: TCP
      targetPort: 8500
    - name: tcp-8400
      port: 8400
      protocol: TCP
      targetPort: 8400
- metadata:
    name: edgex-redis
  spec:
    selector:
      app: edgex-redis
    ports:
    - name: http
      protocol: TCP
      port: 6379
      targetPort: 6379
- metadata:
    name: edgex-support-notifications
  spec:
    selector:
      app: edgex-support-notifications
    ports:
    - name: http
      port: 48060
      protocol: TCP
      targetPort: 48060
- metadata:
    name: edgex-core-metadata
  spec:
    selector:
      app: edgex-core-metadata
    ports:
    - name: http
      port: 48081
      protocol: TCP
      targetPort: 48081
- metadata:
    name: edgex-core-data
  spec:
    selector:
      app: edgex-core-data
    ports:
    - name: tcp-5563
      port: 5563
      protocol: TCP
      targetPort: 5563
    - name: tcp-48080
      port: 48080
      protocol: TCP
      targetPort: 48080
- metadata:
    name: edgex-core-command
  spec:
    selector:
      app: edgex-core-command
    ports:
    - name: http
      port: 48082
      protocol: TCP
      targetPort: 48082
- metadata:
    name: edgex-support-scheduler
  spec:
    selector:
      app: edgex-support-scheduler
    ports:
    - name: http
      port: 48085
      protocol: TCP
      targetPort: 48085
- metadata:
    name: edgex-app-service-configurable-rules
  spec:
    selector:
      app: edgex-app-service-configurable-rules
    ports:
    - name: http
      port: 48100
      protocol: TCP
      targetPort: 48100
deployments:
- metadata:
    name: edgex-core-consul
  spec:
    selector:
      matchLabels:
        app: edgex-core-consul
    template:
      metadata:
        labels:
          app: edgex-core-consul
      spec:
        hostname: edgex-core-consul
        volumes:
          - name: consul-config
            hostPath:
              path: /consul/config
              type: DirectoryOrCreate
          - name: consul-data
            hostPath:
              path: /consul/data
              type: DirectoryOrCreate
          - name: consul-scripts
            hostPath:
              path: /consul/scripts
              type: DirectoryOrCreate
        containers:
        - name: edgex-core-consul
          image: edgexfoundry/docker-edgex-consul:1.3.0
          imagePullPolicy: IfNotPresent
          env:
            - name: EDGEX_DB
              value: "redis"
            - name: EDGEX_SECURE
              value: "false"
          ports:
          - name: tcp-8500
            protocol: TCP
            containerPort: 8500
          - name: tcp-8400
            protocol: TCP
            containerPort: 8400
          volumeMounts:
          - name: consul-config
            mountPath: /consul/config
          - name: consul-data
            mountPath: /consul/data
          - name: consul-scripts
            mountPath: /consul/scripts
- metadata:
    name: edgex-redis
  spec:
    selector:
      matchLabels:
        app: edgex-redis
    template:
      metadata:
        labels:
          app: edgex-redis
      spec:
        hostname: edgex-redis
        volumes:
          - name: db-data
            hostPath:
              path: /data
              type: DirectoryOrCreate
        containers:
        - name: edgex-redis
          image: redis:6.0.9-alpine
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 6379
          envFrom:
          - configMapRef:
              name: common-variables
          volumeMounts:
          - name: db-data
            mountPath: /data
- metadata:
    name: edgex-support-notifications
  spec:
    selector:
      matchLabels:
        app: edgex-support-notifications
    template:
      metadata:
        labels:
          app: edgex-support-notifications
      spec:
        hostname: edgex-support-notifications
        containers:
        - name: edgex-support-notifications
          image: edgexfoundry/docker-support-notifications-go:1.3.0
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: common-variables
          env:
          - name: Service_Host
            value: "edgex-support-notifications"
          ports:
          - name: http
            protocol: TCP
            containerPort: 48060
- metadata:
    name: edgex-core-metadata
  spec:
    selector:
      matchLabels:
        app: edgex-core-metadata
    template:
      metadata:
        labels:
          app: edgex-core-metadata
      spec:
        hostname: edgex-core-metadata
        containers:
        - name: edgex-core-metadata
          image: edgexfoundry/docker-core-metadata-go:1.3.0
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            protocol: TCP
            containerPort: 48081
          envFrom:
          - configMapRef:
              name: common-variables
          env:
          - name: Service_Host
            value: "edgex-core-metadata"
          - name: Notifications_Sender
            value: "edgex-core-metadata"
- metadata:
    name: edgex-core-data
  spec:
    selector:
      matchLabels:
        app: edgex-core-data
    template:
      metadata:
        labels:
          app: edgex-core-data
      spec:
        hostname: edgex-core-data
        containers:
        - name: edgex-core-data
          image: edgexfoundry/docker-core-data-go:1.3.0
          imagePullPolicy: IfNotPresent
          ports:
          - name: tcp-48080
            protocol: TCP
            containerPort: 48080
          - name: tcp-5563
            protocol: TCP
            containerPort: 5563
          envFrom:
          - configMapRef:
              name: common-variables
          env:
          - name: Service_Host
            value: "edgex-core-data"
- metadata:
    name: edgex-core-command
  spec:
    selector:
      matchLabels:
        app: edgex-core-command
    template:
      metadata:
        labels:
          app: edgex-core-command
      spec:
        hostname: edgex-core-command
        containers:
        - name: edgex-core-command
          image: edgexfoundry/docker-core-command-go:1.3.0
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            protocol: TCP
            containerPort: 48082
          envFrom:
          - configMapRef:
              name: common-variables
          env:
          - name: Service_Host
            value: "edgex-core-command"
- metadata:
    name: edgex-support-scheduler
  spec:
    selector:
      matchLabels:
        app: edgex-support-scheduler
    template:
      metadata:
        labels:
          app: edgex-support-scheduler
      spec:
        hostname: edgex-support-scheduler
        containers:
        - name: edgex-support-scheduler
          image: edgexfoundry/docker-support-scheduler-go:1.3.0
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            protocol: TCP
            containerPort: 48085
          envFrom:
          - configMapRef:
              name: common-variables
          env:
          - name: Service_Host
            value: "edgex-support-scheduler"
          - name: IntervalActions_ScrubPushed_Host
            value: "edgex-core-data"
          - name: IntervalActions_ScrubAged_Host
            value: "edgex-core-data"
- metadata:
    name: edgex-app-service-configurable-rules
  spec:
    selector:
      matchLabels:
        app: edgex-app-service-configurable-rules
    template:
      metadata:
        labels:
          app: edgex-app-service-configurable-rules
      spec:
        hostname: edgex-app-service-configurable-rules
        containers:
        - name: edgex-app-service-configurable-rules
          image: edgexfoundry/docker-app-service-configurable:1.3.0
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            protocol: TCP
            containerPort: 48100
          envFrom:
          - configMapRef:
              name: common-variables
          env:
          - name: Service_Host
            value: "edgex-app-service-configurable-rules"
          - name: Service_Port
            value: "48100"
          - name: edgex_profile
            value: "rules-engine"
          - name: MessageBus_SubscribeHost_Host
            value: "edgex-core-data"
          - name: Binding_PublishTopic
            value: "events"
