name: e2e-suite

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install ginkgo
      run: sudo apt-get install golang-ginkgo-dev

    - name: Install curl
      run: sudo apt-get install curl

    - name: Install helm
      run: sudo curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Turn off swap
      run: sudo swapoff -a

    - name: Set netfilter conntrack max
      run: sudo sysctl -w net.netfilter.nf_conntrack_max=131072

    - name: Run PR-Blocking e2e tests
      run: make test-e2e IMG=yurt-edgex-manager
