name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

env:
  ALI_REGISTRY: registry.cn-hangzhou.aliyuncs.com/openyurt

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push DockerHub
        run: TAG=${GITHUB_REF_NAME} make docker-push-mutiarch

      - name: Login to ALI_REGISTRY
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ALI_REGISTRY }}
          username: ${{ secrets.ALI_REGISTRY_USERNAME }}
          password: ${{ secrets.ALI_REGISTRY_PASSWORD }}

      - name: Push ALI_REGISTRY
        run: TAG=${GITHUB_REF_NAME} STAGING_REGISTRY=${{ env.ALI_REGISTRY }} make docker-push-mutiarch

      - name: make documentation
        run: make install-file

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            Documentation/yurt-edgex-manager.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}