name: sync-images

on:
  push: 
    branches: [ main ]

env:
  DOCKERHUB_REGISTRY: docker.io
  ALI_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  REPO: openyurt
  THREAD: 4

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install curl
      run: sudo apt-get install curl

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Sync images to DockerHub
      run: REGISTRY=${{ env.DOCKERHUB_REGISTRY }} REPO=${{ env.REPO }} THREAD=${{ env.THREAD }} make sync_image

    - name: Login to ALI_REGISTRY
      uses: docker/login-action@v1
      with:
        registry: ${{ env.ALI_REGISTRY }}
        username: ${{ secrets.ALI_REGISTRY_USERNAME }}
        password: ${{ secrets.ALI_REGISTRY_PASSWORD }}

    - name: Sync images to ALI_REGISTRY
      run: REGISTRY=${{ env.ALI_REGISTRY }} REPO=${{ env.REPO }} THREAD=${{ env.THREAD }} make sync_image