name: sync-images

on:
  push:
  pull_request:
    branches: [ main ]

env:
  ALI_REGISTRY: registry.cn-hangzhou.aliyuncs.com/openyurt

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.ALI_REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Install curl
      run: sudo apt-get install curl
    - name: Execute sync-images shell script
      run: make sync_image